esphome:
  name: esp-livingroom-ir
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.100.102.59
    gateway: 10.100.102.1
    subnet: 255.255.255.0
  #use_address: 10.100.102.58
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Nodemcuv3"
    password: !secret esp-livingroom-ap-password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#IR Receiver
remote_receiver:
  id: livingroom_ir_receiver
  pin:
    number: D2
    inverted: true
    mode: INPUT_PULLUP
  dump: all
  filter: 10us

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

climate:
  - platform: coolix
    name: "Livingroom A/C"
    sensor: temperature_sensor_livingroom
    receiver_id: livingroom_ir_receiver
# Individual switches
switch:
  - platform: gpio
    name: "livingroom esp led"
    pin: 
      number: D4
      inverted: true
  - platform: template
    name: "Gold Line Fan On/Off"
    turn_on_action:
      remote_transmitter.transmit_rc_switch_raw:
        code: '11011000000'
        protocol: 1
  - platform: template
    name: "Gold Line Fan Speed"
    turn_on_action:
      remote_transmitter.transmit_rc_switch_raw:
        code: '11011000001'
        protocol: 4
  - platform: template
    name: "Gold Line Fan Swing"
    turn_on_action:
      remote_transmitter.transmit_rc_switch_raw:
        code: '11011000010'
        protocol: 4
  - platform: template
    name: "Gold Line Fan Timer"
    turn_on_action:
      remote_transmitter.transmit_rc_switch_raw:
        code: '11011000100'
        protocol: 1
sensor:
  - platform: dht
    pin: D0
    temperature:
      name: "Temperature at livingroom"
      id: temperature_sensor_livingroom
      filters:
        - lambda: return x -2;
    humidity:
      name: "Humidity at livingroom"
      id: humidity_sensor_livingroom
      filters:
        - lambda: return x - 5;

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Livingroom motion PIR sensor"
    id: pir_sensor_livingroom
    device_class: motion