esphome:
  name: esp-basement
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #reboot_timeout: 120s
  manual_ip:
    static_ip: 10.100.102.58
    gateway: 10.100.102.1
    subnet: 255.255.255.0
  #use_address: 10.100.102.58
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Basement Fallback Hotspot"
    password: !secret esp-basement-ap-password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    model: DHT11
    pin: GPIO2
    temperature:
      name: "Basement Temperature"
      id: temperature_basement
    humidity:
      name: "Basement Humidity"
      id: humidity_basment

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "Basement Motion Sensor"
    id: pir_basement
    device_class: motion